# Generated by Django 3.1.1 on 2020-09-09 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentcrud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='stud_contact',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='stud_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='stud_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='stud_id',
        ),
    ]
